package com.sygic.aura;

import android.support.design.C0001R;
import android.support.v7.appcompat.C0101R;

/* renamed from: com.sygic.aura.R */
public final class C1090R {

    /* renamed from: com.sygic.aura.R.styleable */
    public static final class styleable {
        public static final int[] ActionBar;
        public static final int[] ActionBarLayout;
        public static final int ActionBarLayout_android_layout_gravity = 0;
        public static final int ActionBar_abButtonBg = 29;
        public static final int ActionBar_abMode = 27;
        public static final int ActionBar_abTheme = 28;
        public static final int ActionBar_abTitle = 26;
        public static final int ActionBar_background = 10;
        public static final int ActionBar_backgroundSplit = 12;
        public static final int ActionBar_backgroundStacked = 11;
        public static final int ActionBar_contentInsetEnd = 21;
        public static final int ActionBar_contentInsetLeft = 22;
        public static final int ActionBar_contentInsetRight = 23;
        public static final int ActionBar_contentInsetStart = 20;
        public static final int ActionBar_customNavigationLayout = 13;
        public static final int ActionBar_displayOptions = 3;
        public static final int ActionBar_divider = 9;
        public static final int ActionBar_elevation = 24;
        public static final int ActionBar_height = 0;
        public static final int ActionBar_hideOnContentScroll = 19;
        public static final int ActionBar_homeAsUpIndicator = 30;
        public static final int ActionBar_homeLayout = 14;
        public static final int ActionBar_icon = 7;
        public static final int ActionBar_indeterminateProgressStyle = 16;
        public static final int ActionBar_itemPadding = 18;
        public static final int ActionBar_logo = 8;
        public static final int ActionBar_navigationMode = 2;
        public static final int ActionBar_popupTheme = 25;
        public static final int ActionBar_progressBarPadding = 17;
        public static final int ActionBar_progressBarStyle = 15;
        public static final int ActionBar_subtitle = 4;
        public static final int ActionBar_subtitleTextStyle = 6;
        public static final int ActionBar_title = 1;
        public static final int ActionBar_titleTextStyle = 5;
        public static final int[] ActionMenuItemView;
        public static final int ActionMenuItemView_android_minWidth = 0;
        public static final int[] ActionMenuView;
        public static final int[] ActionMode;
        public static final int ActionMode_background = 3;
        public static final int ActionMode_backgroundSplit = 4;
        public static final int ActionMode_closeItemLayout = 5;
        public static final int ActionMode_height = 0;
        public static final int ActionMode_subtitleTextStyle = 2;
        public static final int ActionMode_titleTextStyle = 1;
        public static final int[] ActivityChooserView;
        public static final int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
        public static final int ActivityChooserView_initialActivityCount = 0;
        public static final int[] AdsAttrs;
        public static final int AdsAttrs_adSize = 0;
        public static final int AdsAttrs_adSizes = 1;
        public static final int AdsAttrs_adUnitId = 2;
        public static final int[] AlertDialog;
        public static final int AlertDialog_android_layout = 0;
        public static final int AlertDialog_buttonPanelSideLayout = 1;
        public static final int AlertDialog_listItemLayout = 5;
        public static final int AlertDialog_listLayout = 2;
        public static final int AlertDialog_multiChoiceItemLayout = 3;
        public static final int AlertDialog_singleChoiceItemLayout = 4;
        public static final int[] AppBarLayout;
        public static final int[] AppBarLayout_LayoutParams;
        public static final int AppBarLayout_LayoutParams_layout_scrollFlags = 0;
        public static final int AppBarLayout_LayoutParams_layout_scrollInterpolator = 1;
        public static final int AppBarLayout_android_background = 0;
        public static final int AppBarLayout_elevation = 1;
        public static final int[] AppCompatTextView;
        public static final int AppCompatTextView_android_textAppearance = 0;
        public static final int AppCompatTextView_textAllCaps = 1;
        public static final int[] BluetoothPreference;
        public static final int BluetoothPreference_defaultHfpDelay = 0;
        public static final int[] BubbleSearchBar;
        public static final int BubbleSearchBar_simpleTheme = 0;
        public static final int[] BubbleView;
        public static final int BubbleView_layout = 0;
        public static final int[] CirclePageIndicator;
        public static final int CirclePageIndicator_android_background = 1;
        public static final int CirclePageIndicator_android_orientation = 0;
        public static final int CirclePageIndicator_centered = 2;
        public static final int CirclePageIndicator_fillColor = 3;
        public static final int CirclePageIndicator_pageColor = 4;
        public static final int CirclePageIndicator_radius = 5;
        public static final int CirclePageIndicator_snap = 6;
        public static final int CirclePageIndicator_strokeColor = 7;
        public static final int CirclePageIndicator_strokeWidth = 8;
        public static final int[] CircleProgressBar;
        public static final int CircleProgressBar_max = 0;
        public static final int CircleProgressBar_min = 1;
        public static final int CircleProgressBar_progress = 2;
        public static final int CircleProgressBar_progressBarThickness = 4;
        public static final int CircleProgressBar_progressbarColor = 3;
        public static final int[] CollapsingAppBarLayout_LayoutParams;
        public static final int CollapsingAppBarLayout_LayoutParams_layout_collapseMode = 0;
        public static final int f1252xad49a364 = 1;
        public static final int[] CollapsingToolbarLayout;
        public static final int CollapsingToolbarLayout_collapsedTitleTextAppearance = 6;
        public static final int CollapsingToolbarLayout_contentScrim = 7;
        public static final int CollapsingToolbarLayout_expandedTitleMargin = 0;
        public static final int CollapsingToolbarLayout_expandedTitleMarginBottom = 4;
        public static final int CollapsingToolbarLayout_expandedTitleMarginEnd = 3;
        public static final int CollapsingToolbarLayout_expandedTitleMarginStart = 1;
        public static final int CollapsingToolbarLayout_expandedTitleMarginTop = 2;
        public static final int CollapsingToolbarLayout_expandedTitleTextAppearance = 5;
        public static final int CollapsingToolbarLayout_statusBarScrim = 8;
        public static final int CollapsingToolbarLayout_toolbarId = 9;
        public static final int[] CoordinatorLayout;
        public static final int[] CoordinatorLayout_LayoutParams;
        public static final int CoordinatorLayout_LayoutParams_android_layout_gravity = 0;
        public static final int CoordinatorLayout_LayoutParams_layout_anchor = 2;
        public static final int CoordinatorLayout_LayoutParams_layout_anchorGravity = 4;
        public static final int CoordinatorLayout_LayoutParams_layout_behavior = 1;
        public static final int CoordinatorLayout_LayoutParams_layout_keyline = 3;
        public static final int CoordinatorLayout_keylines = 0;
        public static final int CoordinatorLayout_statusBarBackground = 1;
        public static final int[] DialogSwitchPreference;
        public static final int DialogSwitchPreference_dialogMessage = 0;
        public static final int DialogSwitchPreference_dialogTitle = 1;
        public static final int DialogSwitchPreference_negativeButtonText = 2;
        public static final int DialogSwitchPreference_positiveButtonText = 3;
        public static final int DialogSwitchPreference_premium = 4;
        public static final int[] DiscountTextView;
        public static final int DiscountTextView_discountTextViewStyle = 0;
        public static final int[] DragSortListView;
        public static final int DragSortListView_click_remove_id = 16;
        public static final int DragSortListView_collapsed_height = 0;
        public static final int DragSortListView_drag_enabled = 10;
        public static final int DragSortListView_drag_handle_id = 14;
        public static final int DragSortListView_drag_scroll_start = 1;
        public static final int DragSortListView_drag_start_mode = 13;
        public static final int DragSortListView_drop_animation_duration = 9;
        public static final int DragSortListView_fling_handle_id = 15;
        public static final int DragSortListView_float_alpha = 6;
        public static final int DragSortListView_float_background_res = 3;
        public static final int DragSortListView_max_drag_scroll_speed = 2;
        public static final int DragSortListView_remove_animation_duration = 8;
        public static final int DragSortListView_remove_enabled = 12;
        public static final int DragSortListView_remove_mode = 4;
        public static final int DragSortListView_slide_shuffle_speed = 7;
        public static final int DragSortListView_sort_enabled = 11;
        public static final int DragSortListView_track_drag_sort = 5;
        public static final int DragSortListView_use_default_controller = 17;
        public static final int[] DrawerArrowToggle;
        public static final int DrawerArrowToggle_barSize = 6;
        public static final int DrawerArrowToggle_color = 0;
        public static final int DrawerArrowToggle_drawableSize = 2;
        public static final int DrawerArrowToggle_gapBetweenBars = 3;
        public static final int DrawerArrowToggle_middleBarArrowSize = 5;
        public static final int DrawerArrowToggle_spinBars = 1;
        public static final int DrawerArrowToggle_thickness = 7;
        public static final int DrawerArrowToggle_topBottomBarArrowSize = 4;
        public static final int[] FloatingActionButton;
        public static final int FloatingActionButton_android_background = 0;
        public static final int FloatingActionButton_backgroundTint = 8;
        public static final int FloatingActionButton_backgroundTintMode = 9;
        public static final int FloatingActionButton_borderWidth = 5;
        public static final int FloatingActionButton_elevation = 1;
        public static final int FloatingActionButton_fabBackground = 7;
        public static final int FloatingActionButton_fabIcon = 6;
        public static final int FloatingActionButton_fabSize = 3;
        public static final int FloatingActionButton_pressedTranslationZ = 4;
        public static final int FloatingActionButton_rippleColor = 2;
        public static final int[] FocusableKeyboardView;
        public static final int FocusableKeyboardView_keyBackground = 1;
        public static final int FocusableKeyboardView_keyFocusBackground = 2;
        public static final int FocusableKeyboardView_keyTextColor = 3;
        public static final int FocusableKeyboardView_keyTextSize = 5;
        public static final int FocusableKeyboardView_keyboardViewStyle = 0;
        public static final int FocusableKeyboardView_labelTextSize = 6;
        public static final int FocusableKeyboardView_shadowColor = 4;
        public static final int FocusableKeyboardView_shadowRadius = 7;
        public static final int FocusableKeyboardView_verticalCorrection = 8;
        public static final int[] FontDrawable;
        public static final int FontDrawable_android_text = 2;
        public static final int FontDrawable_android_textColor = 1;
        public static final int FontDrawable_android_textSize = 0;
        public static final int FontDrawable_font = 3;
        public static final int[] ForegroundLinearLayout;
        public static final int ForegroundLinearLayout_android_foreground = 0;
        public static final int[] FragmentPreference;
        public static final int FragmentPreference_fragment_class = 0;
        public static final int FragmentPreference_fragment_data = 1;
        public static final int FragmentPreference_updatable = 2;
        public static final int[] GpsInputPreference;
        public static final int GpsInputPreference_inputType = 0;
        public static final int[] ICSSpinner;
        public static final int ICSSpinner_android_dropDownHorizontalOffset = 5;
        public static final int ICSSpinner_android_dropDownSelector = 1;
        public static final int ICSSpinner_android_dropDownVerticalOffset = 6;
        public static final int ICSSpinner_android_dropDownWidth = 4;
        public static final int ICSSpinner_android_gravity = 0;
        public static final int ICSSpinner_android_popupBackground = 2;
        public static final int ICSSpinner_android_prompt = 3;
        public static final int ICSSpinner_popupPromptView = 7;
        public static final int[] IconTextPreference;
        public static final int IconTextPreference_iconStringRes = 1;
        public static final int IconTextPreference_useIconTextLayout = 0;
        public static final int[] LanguageListPreference;
        public static final int LanguageListPreference_keySecondary = 0;
        public static final int[] LazyImageView;
        public static final int LazyImageView_android_scaleType = 0;
        public static final int[] LinearLayoutCompat;
        public static final int[] LinearLayoutCompat_Layout;
        public static final int LinearLayoutCompat_Layout_android_layout_gravity = 0;
        public static final int LinearLayoutCompat_Layout_android_layout_height = 2;
        public static final int LinearLayoutCompat_Layout_android_layout_weight = 3;
        public static final int LinearLayoutCompat_Layout_android_layout_width = 1;
        public static final int LinearLayoutCompat_android_baselineAligned = 2;
        public static final int LinearLayoutCompat_android_baselineAlignedChildIndex = 3;
        public static final int LinearLayoutCompat_android_gravity = 0;
        public static final int LinearLayoutCompat_android_orientation = 1;
        public static final int LinearLayoutCompat_android_weightSum = 4;
        public static final int LinearLayoutCompat_divider = 5;
        public static final int LinearLayoutCompat_dividerPadding = 8;
        public static final int LinearLayoutCompat_measureWithLargestChild = 6;
        public static final int LinearLayoutCompat_showDividers = 7;
        public static final int[] ListPopupWindow;
        public static final int ListPopupWindow_android_dropDownHorizontalOffset = 0;
        public static final int ListPopupWindow_android_dropDownVerticalOffset = 1;
        public static final int[] LoadingImageView;
        public static final int LoadingImageView_circleCrop = 2;
        public static final int LoadingImageView_imageAspectRatio = 1;
        public static final int LoadingImageView_imageAspectRatioAdjust = 0;
        public static final int[] LoginDetailsPreference;
        public static final int LoginDetailsPreference_load_name = 2;
        public static final int LoginDetailsPreference_show_name = 0;
        public static final int LoginDetailsPreference_show_password = 1;
        public static final int[] MapAttrs;
        public static final int MapAttrs_cameraBearing = 1;
        public static final int MapAttrs_cameraTargetLat = 2;
        public static final int MapAttrs_cameraTargetLng = 3;
        public static final int MapAttrs_cameraTilt = 4;
        public static final int MapAttrs_cameraZoom = 5;
        public static final int MapAttrs_liteMode = 6;
        public static final int MapAttrs_mapType = 0;
        public static final int MapAttrs_uiCompass = 7;
        public static final int MapAttrs_uiMapToolbar = 15;
        public static final int MapAttrs_uiRotateGestures = 8;
        public static final int MapAttrs_uiScrollGestures = 9;
        public static final int MapAttrs_uiTiltGestures = 10;
        public static final int MapAttrs_uiZoomControls = 11;
        public static final int MapAttrs_uiZoomGestures = 12;
        public static final int MapAttrs_useViewLifecycle = 13;
        public static final int MapAttrs_zOrderOnTop = 14;
        public static final int[] MenuGroup;
        public static final int MenuGroup_android_checkableBehavior = 5;
        public static final int MenuGroup_android_enabled = 0;
        public static final int MenuGroup_android_id = 1;
        public static final int MenuGroup_android_menuCategory = 3;
        public static final int MenuGroup_android_orderInCategory = 4;
        public static final int MenuGroup_android_visible = 2;
        public static final int[] MenuItem;
        public static final int MenuItem_actionLayout = 14;
        public static final int MenuItem_actionProviderClass = 16;
        public static final int MenuItem_actionViewClass = 15;
        public static final int MenuItem_android_alphabeticShortcut = 9;
        public static final int MenuItem_android_checkable = 11;
        public static final int MenuItem_android_checked = 3;
        public static final int MenuItem_android_enabled = 1;
        public static final int MenuItem_android_icon = 0;
        public static final int MenuItem_android_id = 2;
        public static final int MenuItem_android_menuCategory = 5;
        public static final int MenuItem_android_numericShortcut = 10;
        public static final int MenuItem_android_onClick = 12;
        public static final int MenuItem_android_orderInCategory = 6;
        public static final int MenuItem_android_title = 7;
        public static final int MenuItem_android_titleCondensed = 8;
        public static final int MenuItem_android_visible = 4;
        public static final int MenuItem_showAsAction = 13;
        public static final int[] MenuView;
        public static final int MenuView_android_headerBackground = 4;
        public static final int MenuView_android_horizontalDivider = 2;
        public static final int MenuView_android_itemBackground = 5;
        public static final int MenuView_android_itemIconDisabledAlpha = 6;
        public static final int MenuView_android_itemTextAppearance = 1;
        public static final int MenuView_android_verticalDivider = 3;
        public static final int MenuView_android_windowAnimationStyle = 0;
        public static final int MenuView_preserveIconSpacing = 7;
        public static final int[] NavigationView;
        public static final int NavigationView_android_background = 0;
        public static final int NavigationView_android_fitsSystemWindows = 1;
        public static final int NavigationView_android_maxWidth = 2;
        public static final int NavigationView_elevation = 3;
        public static final int NavigationView_headerLayout = 8;
        public static final int NavigationView_itemBackground = 7;
        public static final int NavigationView_itemIconTint = 5;
        public static final int NavigationView_itemTextColor = 6;
        public static final int NavigationView_menu = 4;
        public static final int[] NotificationCenterView;
        public static final int NotificationCenterView_accepts = 0;
        public static final int[] PopupWindow;
        public static final int[] PopupWindowBackgroundState;
        public static final int PopupWindowBackgroundState_state_above_anchor = 0;
        public static final int PopupWindow_android_popupBackground = 0;
        public static final int PopupWindow_overlapAnchor = 1;
        public static final int[] QuickMenuItem;
        public static final int QuickMenuItem_quickMenuType = 0;
        public static final int[] SButton;
        public static final int SButton_font = 0;
        public static final int SButton_textId = 1;
        public static final int SButton_textStyle = 2;
        public static final int[] SCheckBox;
        public static final int SCheckBox_font = 0;
        public static final int SCheckBox_textId = 1;
        public static final int SCheckBox_textStyle = 2;
        public static final int SCheckBox_themeStyle = 3;
        public static final int[] SEditText;
        public static final int SEditText_font = 0;
        public static final int SEditText_hintId = 1;
        public static final int SEditText_textId = 2;
        public static final int SEditText_textStyle = 3;
        public static final int[] SForegroundImageView;
        public static final int SForegroundImageView_android_foreground = 0;
        public static final int[] SImageButton;
        public static final int SImageButton_inCarScale = 0;
        public static final int SImageButton_textSrc = 1;
        public static final int[] SImageView;
        public static final int SImageView_textSrc = 0;
        public static final int[] SRotatedTextView;
        public static final int SRotatedTextView_rotation = 0;
        public static final int[] STextView;
        public static final int STextView_dynamicResize = 5;
        public static final int STextView_dynamicResizeHeight = 6;
        public static final int STextView_font = 0;
        public static final int STextView_hintId = 1;
        public static final int STextView_inCarScale = 2;
        public static final int STextView_maxTextSize = 7;
        public static final int STextView_minTextSize = 8;
        public static final int STextView_textId = 3;
        public static final int STextView_textStyle = 4;
        public static final int[] SToggleButton;
        public static final int SToggleButton_colorOff = 6;
        public static final int SToggleButton_colorOn = 5;
        public static final int SToggleButton_font = 0;
        public static final int SToggleButton_textId = 1;
        public static final int SToggleButton_textSrcOff = 4;
        public static final int SToggleButton_textSrcOn = 3;
        public static final int SToggleButton_textStyle = 2;
        public static final int[] ScrimInsetsFrameLayout;
        public static final int ScrimInsetsFrameLayout_insetForeground = 0;
        public static final int[] ScrollingViewBehavior_Params;
        public static final int ScrollingViewBehavior_Params_behavior_overlapTop = 0;
        public static final int[] SearchView;
        public static final int SearchView_android_focusable = 0;
        public static final int SearchView_android_imeOptions = 3;
        public static final int SearchView_android_inputType = 2;
        public static final int SearchView_android_maxWidth = 1;
        public static final int SearchView_closeIcon = 8;
        public static final int SearchView_commitIcon = 13;
        public static final int SearchView_defaultQueryHint = 7;
        public static final int SearchView_goIcon = 9;
        public static final int SearchView_iconifiedByDefault = 5;
        public static final int SearchView_layout = 4;
        public static final int SearchView_queryBackground = 15;
        public static final int SearchView_queryHint = 6;
        public static final int SearchView_searchHintIcon = 11;
        public static final int SearchView_searchIcon = 10;
        public static final int SearchView_submitBackground = 16;
        public static final int SearchView_suggestionRowLayout = 14;
        public static final int SearchView_voiceIcon = 12;
        public static final int[] SeekBarPreference;
        public static final int SeekBarPreference_rangeMax = 0;
        public static final int[] SeekBarsPreference;
        public static final int SeekBarsPreference_formaterTypePrimary = 11;
        public static final int SeekBarsPreference_formaterTypeSecondary = 12;
        public static final int SeekBarsPreference_formaterTypeTertiary = 13;
        public static final int SeekBarsPreference_formatterCustomValuesPrimary = 14;
        public static final int SeekBarsPreference_formatterCustomValuesSecondary = 15;
        public static final int SeekBarsPreference_formatterCustomValuesTertiary = 16;
        public static final int SeekBarsPreference_iconSecondary = 5;
        public static final int SeekBarsPreference_iconTertiary = 6;
        public static final int SeekBarsPreference_keySecondary = 0;
        public static final int SeekBarsPreference_keyTertiary = 1;
        public static final int SeekBarsPreference_message = 10;
        public static final int SeekBarsPreference_rangeMaxPrimary = 7;
        public static final int SeekBarsPreference_rangeMaxSecondary = 8;
        public static final int SeekBarsPreference_rangeMaxTertiary = 9;
        public static final int SeekBarsPreference_titleSeekBarPrimary = 2;
        public static final int SeekBarsPreference_titleSeekBarSecondary = 3;
        public static final int SeekBarsPreference_titleSeekBarTertiary = 4;
        public static final int[] SettingsFragmentPreference;
        public static final int SettingsFragmentPreference_fragmentClassName = 4;
        public static final int SettingsFragmentPreference_lastDivider = 2;
        public static final int SettingsFragmentPreference_preferences = 1;
        public static final int SettingsFragmentPreference_premium = 0;
        public static final int SettingsFragmentPreference_premiumFeatures = 5;
        public static final int SettingsFragmentPreference_registerOnChange = 3;
        public static final int[] ShowcaseView;
        public static final int ShowcaseView_sv_backgroundColor = 0;
        public static final int ShowcaseView_sv_detailTextAppearance = 1;
        public static final int ShowcaseView_sv_titleTextAppearance = 2;
        public static final int[] SlideView;
        public static final int SlideView_viewLeft = 1;
        public static final int SlideView_viewRight = 0;
        public static final int[] SmartProgressBar;
        public static final int SmartProgressBar_actionColor = 3;
        public static final int SmartProgressBar_actionSelector = 4;
        public static final int SmartProgressBar_actionString = 1;
        public static final int SmartProgressBar_errorImage = 5;
        public static final int SmartProgressBar_imageColor = 6;
        public static final int SmartProgressBar_messageColor = 2;
        public static final int SmartProgressBar_messageString = 0;
        public static final int[] SnackbarLayout;
        public static final int SnackbarLayout_android_maxWidth = 0;
        public static final int SnackbarLayout_elevation = 1;
        public static final int SnackbarLayout_maxActionInlineWidth = 2;
        public static final int[] SosSectionView;
        public static final int SosSectionView_sosIcon = 0;
        public static final int SosSectionView_sosLabel = 1;
        public static final int[] SpanVariableGridView;
        public static final int SpanVariableGridView_itemMargin = 2;
        public static final int SpanVariableGridView_itemsOrientation = 3;
        public static final int SpanVariableGridView_numColumns = 0;
        public static final int SpanVariableGridView_numRows = 1;
        public static final int[] Spinner;
        public static final int Spinner_android_background = 1;
        public static final int Spinner_android_dropDownHorizontalOffset = 5;
        public static final int Spinner_android_dropDownSelector = 2;
        public static final int Spinner_android_dropDownVerticalOffset = 6;
        public static final int Spinner_android_dropDownWidth = 4;
        public static final int Spinner_android_gravity = 0;
        public static final int Spinner_android_popupBackground = 3;
        public static final int Spinner_disableChildrenWhenDisabled = 10;
        public static final int Spinner_popupPromptView = 9;
        public static final int Spinner_prompt = 7;
        public static final int Spinner_spinnerMode = 8;
        public static final int[] StyleableSwitchPreference;
        public static final int StyleableSwitchPreference_premium = 0;
        public static final int[] SwitchCompat;
        public static final int SwitchCompat_android_textOff = 1;
        public static final int SwitchCompat_android_textOn = 0;
        public static final int SwitchCompat_android_thumb = 2;
        public static final int SwitchCompat_showText = 9;
        public static final int SwitchCompat_splitTrack = 8;
        public static final int SwitchCompat_switchMinWidth = 6;
        public static final int SwitchCompat_switchPadding = 7;
        public static final int SwitchCompat_switchTextAppearance = 5;
        public static final int SwitchCompat_thumbTextPadding = 4;
        public static final int SwitchCompat_track = 3;
        public static final int[] TabLayout;
        public static final int TabLayout_tabBackground = 3;
        public static final int TabLayout_tabContentStart = 2;
        public static final int TabLayout_tabGravity = 5;
        public static final int TabLayout_tabIndicatorColor = 0;
        public static final int TabLayout_tabIndicatorHeight = 1;
        public static final int TabLayout_tabMaxWidth = 7;
        public static final int TabLayout_tabMinWidth = 6;
        public static final int TabLayout_tabMode = 4;
        public static final int TabLayout_tabPadding = 15;
        public static final int TabLayout_tabPaddingBottom = 14;
        public static final int TabLayout_tabPaddingEnd = 13;
        public static final int TabLayout_tabPaddingStart = 11;
        public static final int TabLayout_tabPaddingTop = 12;
        public static final int TabLayout_tabSelectedTextColor = 10;
        public static final int TabLayout_tabTextAppearance = 8;
        public static final int TabLayout_tabTextColor = 9;
        public static final int[] TextAppearance;
        public static final int TextAppearance_android_textColor = 3;
        public static final int TextAppearance_android_textSize = 0;
        public static final int TextAppearance_android_textStyle = 2;
        public static final int TextAppearance_android_typeface = 1;
        public static final int TextAppearance_textAllCaps = 4;
        public static final int[] TextInputLayout;
        public static final int TextInputLayout_android_hint = 0;
        public static final int TextInputLayout_errorEnabled = 2;
        public static final int TextInputLayout_errorTextAppearance = 3;
        public static final int TextInputLayout_hintTextAppearance = 1;
        public static final int[] Theme;
        public static final int Theme_actionBarDivider = 23;
        public static final int Theme_actionBarItemBackground = 24;
        public static final int Theme_actionBarPopupTheme = 17;
        public static final int Theme_actionBarSize = 22;
        public static final int Theme_actionBarSplitStyle = 19;
        public static final int Theme_actionBarStyle = 18;
        public static final int Theme_actionBarTabBarStyle = 13;
        public static final int Theme_actionBarTabStyle = 12;
        public static final int Theme_actionBarTabTextStyle = 14;
        public static final int Theme_actionBarTheme = 20;
        public static final int Theme_actionBarWidgetTheme = 21;
        public static final int Theme_actionButtonStyle = 49;
        public static final int Theme_actionDropDownStyle = 45;
        public static final int Theme_actionMenuTextAppearance = 25;
        public static final int Theme_actionMenuTextColor = 26;
        public static final int Theme_actionModeBackground = 29;
        public static final int Theme_actionModeCloseButtonStyle = 28;
        public static final int Theme_actionModeCloseDrawable = 31;
        public static final int Theme_actionModeCopyDrawable = 33;
        public static final int Theme_actionModeCutDrawable = 32;
        public static final int Theme_actionModeFindDrawable = 37;
        public static final int Theme_actionModePasteDrawable = 34;
        public static final int Theme_actionModePopupWindowStyle = 39;
        public static final int Theme_actionModeSelectAllDrawable = 35;
        public static final int Theme_actionModeShareDrawable = 36;
        public static final int Theme_actionModeSplitBackground = 30;
        public static final int Theme_actionModeStyle = 27;
        public static final int Theme_actionModeWebSearchDrawable = 38;
        public static final int Theme_actionOverflowButtonStyle = 15;
        public static final int Theme_actionOverflowMenuStyle = 16;
        public static final int Theme_activityChooserViewStyle = 57;
        public static final int Theme_alertDialogButtonGroupStyle = 90;
        public static final int Theme_alertDialogCenterButtons = 91;
        public static final int Theme_alertDialogStyle = 89;
        public static final int Theme_alertDialogTheme = 92;
        public static final int Theme_android_windowAnimationStyle = 1;
        public static final int Theme_android_windowIsFloating = 0;
        public static final int Theme_autoCompleteTextViewStyle = 97;
        public static final int Theme_borderlessButtonStyle = 54;
        public static final int Theme_buttonBarButtonStyle = 51;
        public static final int Theme_buttonBarNegativeButtonStyle = 95;
        public static final int Theme_buttonBarNeutralButtonStyle = 96;
        public static final int Theme_buttonBarPositiveButtonStyle = 94;
        public static final int Theme_buttonBarStyle = 50;
        public static final int Theme_buttonStyle = 98;
        public static final int Theme_buttonStyleSmall = 99;
        public static final int Theme_checkboxStyle = 100;
        public static final int Theme_checkedTextViewStyle = 101;
        public static final int Theme_colorAccent = 83;
        public static final int Theme_colorButtonNormal = 87;
        public static final int Theme_colorControlActivated = 85;
        public static final int Theme_colorControlHighlight = 86;
        public static final int Theme_colorControlNormal = 84;
        public static final int Theme_colorPrimary = 81;
        public static final int Theme_colorPrimaryDark = 82;
        public static final int Theme_colorSwitchThumbNormal = 88;
        public static final int Theme_dialogPreferredPadding = 43;
        public static final int Theme_dialogTheme = 42;
        public static final int Theme_dividerHorizontal = 56;
        public static final int Theme_dividerVertical = 55;
        public static final int Theme_dropDownListViewStyle = 73;
        public static final int Theme_dropdownListPreferredItemHeight = 46;
        public static final int Theme_editTextBackground = 63;
        public static final int Theme_editTextColor = 62;
        public static final int Theme_editTextStyle = 102;
        public static final int Theme_homeAsUpIndicator = 48;
        public static final int Theme_listChoiceBackgroundIndicator = 80;
        public static final int Theme_listDividerAlertDialog = 44;
        public static final int Theme_listPopupWindowStyle = 74;
        public static final int Theme_listPreferredItemHeight = 68;
        public static final int Theme_listPreferredItemHeightLarge = 70;
        public static final int Theme_listPreferredItemHeightSmall = 69;
        public static final int Theme_listPreferredItemPaddingLeft = 71;
        public static final int Theme_listPreferredItemPaddingRight = 72;
        public static final int Theme_panelBackground = 77;
        public static final int Theme_panelMenuListTheme = 79;
        public static final int Theme_panelMenuListWidth = 78;
        public static final int Theme_popupMenuStyle = 60;
        public static final int Theme_popupWindowStyle = 61;
        public static final int Theme_radioButtonStyle = 103;
        public static final int Theme_ratingBarStyle = 104;
        public static final int Theme_searchViewStyle = 67;
        public static final int Theme_selectableItemBackground = 52;
        public static final int Theme_selectableItemBackgroundBorderless = 53;
        public static final int Theme_spinnerDropDownItemStyle = 47;
        public static final int Theme_spinnerStyle = 105;
        public static final int Theme_switchStyle = 106;
        public static final int Theme_textAppearanceLargePopupMenu = 40;
        public static final int Theme_textAppearanceListItem = 75;
        public static final int Theme_textAppearanceListItemSmall = 76;
        public static final int Theme_textAppearanceSearchResultSubtitle = 65;
        public static final int Theme_textAppearanceSearchResultTitle = 64;
        public static final int Theme_textAppearanceSmallPopupMenu = 41;
        public static final int Theme_textColorAlertDialogListItem = 93;
        public static final int Theme_textColorSearchUrl = 66;
        public static final int Theme_toolbarNavigationButtonStyle = 59;
        public static final int Theme_toolbarStyle = 58;
        public static final int Theme_windowActionBar = 2;
        public static final int Theme_windowActionBarOverlay = 4;
        public static final int Theme_windowActionModeOverlay = 5;
        public static final int Theme_windowFixedHeightMajor = 9;
        public static final int Theme_windowFixedHeightMinor = 7;
        public static final int Theme_windowFixedWidthMajor = 6;
        public static final int Theme_windowFixedWidthMinor = 8;
        public static final int Theme_windowMinWidthMajor = 10;
        public static final int Theme_windowMinWidthMinor = 11;
        public static final int Theme_windowNoTitle = 3;
        public static final int[] ThreeStateButton;
        public static final int ThreeStateButton_state_one = 0;
        public static final int ThreeStateButton_state_three = 2;
        public static final int ThreeStateButton_state_two = 1;
        public static final int[] Toolbar;
        public static final int Toolbar_android_gravity = 0;
        public static final int Toolbar_android_minHeight = 1;
        public static final int Toolbar_collapseContentDescription = 18;
        public static final int Toolbar_collapseIcon = 17;
        public static final int Toolbar_contentInsetEnd = 5;
        public static final int Toolbar_contentInsetLeft = 6;
        public static final int Toolbar_contentInsetRight = 7;
        public static final int Toolbar_contentInsetStart = 4;
        public static final int Toolbar_maxButtonHeight = 16;
        public static final int Toolbar_navigationContentDescription = 20;
        public static final int Toolbar_navigationIcon = 19;
        public static final int Toolbar_popupTheme = 8;
        public static final int Toolbar_subtitle = 3;
        public static final int Toolbar_subtitleTextAppearance = 10;
        public static final int Toolbar_title = 2;
        public static final int Toolbar_titleMarginBottom = 15;
        public static final int Toolbar_titleMarginEnd = 13;
        public static final int Toolbar_titleMarginStart = 12;
        public static final int Toolbar_titleMarginTop = 14;
        public static final int Toolbar_titleMargins = 11;
        public static final int Toolbar_titleTextAppearance = 9;
        public static final int[] View;
        public static final int[] ViewPagerIndicator;
        public static final int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
        public static final int[] ViewStubCompat;
        public static final int ViewStubCompat_android_id = 0;
        public static final int ViewStubCompat_android_inflatedId = 2;
        public static final int ViewStubCompat_android_layout = 1;
        public static final int View_android_focusable = 1;
        public static final int View_android_theme = 0;
        public static final int View_backgroundTint = 5;
        public static final int View_backgroundTintMode = 6;
        public static final int View_paddingEnd = 3;
        public static final int View_paddingStart = 2;
        public static final int View_theme = 4;
        public static final int[] com_facebook_like_view;
        public static final int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
        public static final int com_facebook_like_view_com_facebook_foreground_color = 0;
        public static final int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
        public static final int com_facebook_like_view_com_facebook_object_id = 1;
        public static final int com_facebook_like_view_com_facebook_object_type = 2;
        public static final int com_facebook_like_view_com_facebook_style = 3;
        public static final int[] com_facebook_login_view;
        public static final int com_facebook_login_view_com_facebook_confirm_logout = 0;
        public static final int com_facebook_login_view_com_facebook_login_text = 1;
        public static final int com_facebook_login_view_com_facebook_logout_text = 2;
        public static final int com_facebook_login_view_com_facebook_tooltip_mode = 3;
        public static final int[] com_facebook_profile_picture_view;
        public static final int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
        public static final int com_facebook_profile_picture_view_com_facebook_preset_size = 0;

        static {
            ActionBar = new int[]{C0101R.attr.height, C0101R.attr.title, C0101R.attr.navigationMode, C0101R.attr.displayOptions, C0101R.attr.subtitle, C0101R.attr.titleTextStyle, C0101R.attr.subtitleTextStyle, C0101R.attr.icon, C0101R.attr.logo, C0101R.attr.divider, C0101R.attr.background, C0101R.attr.backgroundStacked, C0101R.attr.backgroundSplit, C0101R.attr.customNavigationLayout, C0101R.attr.homeLayout, C0101R.attr.progressBarStyle, C0101R.attr.indeterminateProgressStyle, C0101R.attr.progressBarPadding, C0101R.attr.itemPadding, C0101R.attr.hideOnContentScroll, C0101R.attr.contentInsetStart, C0101R.attr.contentInsetEnd, C0101R.attr.contentInsetLeft, C0101R.attr.contentInsetRight, C0101R.attr.elevation, C0101R.attr.popupTheme, 2130772021, 2130772022, 2130772023, 2130772024, C0101R.attr.homeAsUpIndicator};
            int[] iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 16842931;
            ActionBarLayout = iArr;
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 16843071;
            ActionMenuItemView = iArr;
            ActionMenuView = new int[com_facebook_login_view_com_facebook_confirm_logout];
            ActionMode = new int[]{C0101R.attr.height, C0101R.attr.titleTextStyle, C0101R.attr.subtitleTextStyle, C0101R.attr.background, C0101R.attr.backgroundSplit, C0101R.attr.closeItemLayout};
            ActivityChooserView = new int[]{C0101R.attr.initialActivityCount, C0101R.attr.expandActivityOverflowButtonDrawable};
            AdsAttrs = new int[]{2130772028, 2130772029, 2130772030};
            AlertDialog = new int[]{16842994, C0101R.attr.buttonPanelSideLayout, C0101R.attr.listLayout, C0101R.attr.multiChoiceItemLayout, C0101R.attr.singleChoiceItemLayout, C0101R.attr.listItemLayout};
            AppBarLayout = new int[]{16842964, C0101R.attr.elevation};
            AppBarLayout_LayoutParams = new int[]{C0001R.attr.layout_scrollFlags, C0001R.attr.layout_scrollInterpolator};
            AppCompatTextView = new int[]{16842804, C0101R.attr.textAllCaps};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130772039;
            BluetoothPreference = iArr;
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130772040;
            BubbleSearchBar = iArr;
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = C0101R.attr.layout;
            BubbleView = iArr;
            CirclePageIndicator = new int[]{16842948, 16842964, 2130772041, 2130772042, 2130772043, 2130772044, 2130772045, 2130772046, 2130772047};
            CircleProgressBar = new int[]{2130771986, 2130771987, 2130771991, 2130772048, 2130772049};
            CollapsingAppBarLayout_LayoutParams = new int[]{C0001R.attr.layout_collapseMode, C0001R.attr.layout_collapseParallaxMultiplier};
            CollapsingToolbarLayout = new int[]{C0001R.attr.expandedTitleMargin, C0001R.attr.expandedTitleMarginStart, C0001R.attr.expandedTitleMarginTop, C0001R.attr.expandedTitleMarginEnd, C0001R.attr.expandedTitleMarginBottom, C0001R.attr.expandedTitleTextAppearance, C0001R.attr.collapsedTitleTextAppearance, C0001R.attr.contentScrim, C0001R.attr.statusBarScrim, C0001R.attr.toolbarId};
            CoordinatorLayout = new int[]{C0001R.attr.keylines, C0001R.attr.statusBarBackground};
            CoordinatorLayout_LayoutParams = new int[]{16842931, C0001R.attr.layout_behavior, C0001R.attr.layout_anchor, C0001R.attr.layout_keyline, C0001R.attr.layout_anchorGravity};
            DialogSwitchPreference = new int[]{2130771974, 2130771975, 2130771988, 2130771989, 2130771990};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130772068;
            DiscountTextView = iArr;
            DragSortListView = new int[]{2130772069, 2130772070, 2130772071, 2130772072, 2130772073, 2130772074, 2130772075, 2130772076, 2130772077, 2130772078, 2130772079, 2130772080, 2130772081, 2130772082, 2130772083, 2130772084, 2130772085, 2130772086};
            DrawerArrowToggle = new int[]{C0101R.attr.color, C0101R.attr.spinBars, C0101R.attr.drawableSize, C0101R.attr.gapBetweenBars, C0101R.attr.topBottomBarArrowSize, C0101R.attr.middleBarArrowSize, C0101R.attr.barSize, C0101R.attr.thickness};
            FloatingActionButton = new int[]{16842964, C0101R.attr.elevation, C0001R.attr.rippleColor, C0001R.attr.fabSize, C0001R.attr.pressedTranslationZ, C0001R.attr.borderWidth, 2130772099, 2130772100, C0101R.attr.backgroundTint, C0101R.attr.backgroundTintMode};
            FocusableKeyboardView = new int[]{2130772101, 2130772102, 2130772103, 2130772104, 2130772105, 2130772106, 2130772107, 2130772108, 2130772109};
            FontDrawable = new int[]{16842901, 16842904, 16843087, 2130771979};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 16843017;
            ForegroundLinearLayout = iArr;
            FragmentPreference = new int[]{2130772110, 2130772111, 2130772112};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130772113;
            GpsInputPreference = iArr;
            ICSSpinner = new int[]{16842927, 16843125, 16843126, 16843131, 16843362, 16843436, 16843437, C0101R.attr.popupPromptView};
            IconTextPreference = new int[]{2130772114, 2130772115};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130771984;
            LanguageListPreference = iArr;
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 16843037;
            LazyImageView = iArr;
            LinearLayoutCompat = new int[]{16842927, 16842948, 16843046, 16843047, 16843048, C0101R.attr.divider, C0101R.attr.measureWithLargestChild, C0101R.attr.showDividers, C0101R.attr.dividerPadding};
            LinearLayoutCompat_Layout = new int[]{16842931, 16842996, 16842997, 16843137};
            ListPopupWindow = new int[]{16843436, 16843437};
            LoadingImageView = new int[]{2130772119, 2130772120, 2130772121};
            LoginDetailsPreference = new int[]{2130772122, 2130772123, 2130772124};
            MapAttrs = new int[]{2130772125, 2130772126, 2130772127, 2130772128, 2130772129, 2130772130, 2130772131, 2130772132, 2130772133, 2130772134, 2130772135, 2130772136, 2130772137, 2130772138, 2130772139, 2130772140};
            MenuGroup = new int[]{16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
            MenuItem = new int[]{16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, C0101R.attr.showAsAction, C0101R.attr.actionLayout, C0101R.attr.actionViewClass, C0101R.attr.actionProviderClass};
            MenuView = new int[]{16842926, 16843052, 16843053, 16843054, 16843055, 16843056, 16843057, C0101R.attr.preserveIconSpacing};
            NavigationView = new int[]{16842964, 16842973, 16843039, C0101R.attr.elevation, C0001R.attr.menu, C0001R.attr.itemIconTint, C0001R.attr.itemTextColor, C0001R.attr.itemBackground, C0001R.attr.headerLayout};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130772151;
            NotificationCenterView = iArr;
            PopupWindow = new int[]{16843126, C0101R.attr.overlapAnchor};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = C0101R.attr.state_above_anchor;
            PopupWindowBackgroundState = iArr;
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130771992;
            QuickMenuItem = iArr;
            SButton = new int[]{2130771979, 2130771993, 2130771995};
            SCheckBox = new int[]{2130771979, 2130771993, 2130771995, 2130772154};
            SEditText = new int[]{2130771979, 2130771981, 2130771993, 2130771995};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 16843017;
            SForegroundImageView = iArr;
            SImageButton = new int[]{2130771982, 2130771994};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130771994;
            SImageView = iArr;
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130772155;
            SRotatedTextView = iArr;
            STextView = new int[]{2130771979, 2130771981, 2130771982, 2130771993, 2130771995, 2130772156, 2130772157, 2130772158, 2130772159};
            SToggleButton = new int[]{2130771979, 2130771993, 2130771995, 2130772160, 2130772161, 2130772162, 2130772163};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = C0001R.attr.insetForeground;
            ScrimInsetsFrameLayout = iArr;
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = C0001R.attr.behavior_overlapTop;
            ScrollingViewBehavior_Params = iArr;
            SearchView = new int[]{16842970, 16843039, 16843296, 16843364, C0101R.attr.layout, C0101R.attr.iconifiedByDefault, C0101R.attr.queryHint, C0101R.attr.defaultQueryHint, C0101R.attr.closeIcon, C0101R.attr.goIcon, C0101R.attr.searchIcon, C0101R.attr.searchHintIcon, C0101R.attr.voiceIcon, C0101R.attr.commitIcon, C0101R.attr.suggestionRowLayout, C0101R.attr.queryBackground, C0101R.attr.submitBackground};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130772179;
            SeekBarPreference = iArr;
            SeekBarsPreference = new int[]{2130771984, 2130771985, 2130772180, 2130772181, 2130772182, 2130772183, 2130772184, 2130772185, 2130772186, 2130772187, 2130772188, 2130772189, 2130772190, 2130772191, 2130772192, 2130772193, 2130772194};
            SettingsFragmentPreference = new int[]{2130771990, 2130772195, 2130772196, 2130772197, 2130772198, 2130772199};
            ShowcaseView = new int[]{2130772200, 2130772201, 2130772202};
            SlideView = new int[]{2130772203, 2130772204};
            SmartProgressBar = new int[]{2130772205, 2130772206, 2130772207, 2130772208, 2130772209, 2130772210, 2130772211};
            SnackbarLayout = new int[]{16843039, C0101R.attr.elevation, C0001R.attr.maxActionInlineWidth};
            SosSectionView = new int[]{2130772213, 2130772214};
            SpanVariableGridView = new int[]{2130772215, 2130772216, 2130772217, 2130772218};
            Spinner = new int[]{16842927, 16842964, 16843125, 16843126, 16843362, 16843436, 16843437, C0101R.attr.prompt, C0101R.attr.spinnerMode, C0101R.attr.popupPromptView, C0101R.attr.disableChildrenWhenDisabled};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130771990;
            StyleableSwitchPreference = iArr;
            SwitchCompat = new int[]{16843044, 16843045, 16843074, C0101R.attr.track, C0101R.attr.thumbTextPadding, C0101R.attr.switchTextAppearance, C0101R.attr.switchMinWidth, C0101R.attr.switchPadding, C0101R.attr.splitTrack, C0101R.attr.showText};
            TabLayout = new int[]{C0001R.attr.tabIndicatorColor, C0001R.attr.tabIndicatorHeight, C0001R.attr.tabContentStart, C0001R.attr.tabBackground, C0001R.attr.tabMode, C0001R.attr.tabGravity, C0001R.attr.tabMinWidth, C0001R.attr.tabMaxWidth, C0001R.attr.tabTextAppearance, C0001R.attr.tabTextColor, C0001R.attr.tabSelectedTextColor, C0001R.attr.tabPaddingStart, C0001R.attr.tabPaddingTop, C0001R.attr.tabPaddingEnd, C0001R.attr.tabPaddingBottom, C0001R.attr.tabPadding};
            TextAppearance = new int[]{16842901, 16842902, 16842903, 16842904, C0101R.attr.textAllCaps};
            TextInputLayout = new int[]{16843088, C0001R.attr.hintTextAppearance, C0001R.attr.errorEnabled, C0001R.attr.errorTextAppearance};
            Theme = new int[]{16842839, 16842926, C0101R.attr.windowActionBar, C0101R.attr.windowNoTitle, C0101R.attr.windowActionBarOverlay, C0101R.attr.windowActionModeOverlay, C0101R.attr.windowFixedWidthMajor, C0101R.attr.windowFixedHeightMinor, C0101R.attr.windowFixedWidthMinor, C0101R.attr.windowFixedHeightMajor, C0101R.attr.windowMinWidthMajor, C0101R.attr.windowMinWidthMinor, C0101R.attr.actionBarTabStyle, C0101R.attr.actionBarTabBarStyle, C0101R.attr.actionBarTabTextStyle, C0101R.attr.actionOverflowButtonStyle, C0101R.attr.actionOverflowMenuStyle, C0101R.attr.actionBarPopupTheme, C0101R.attr.actionBarStyle, C0101R.attr.actionBarSplitStyle, C0101R.attr.actionBarTheme, C0101R.attr.actionBarWidgetTheme, C0101R.attr.actionBarSize, C0101R.attr.actionBarDivider, C0101R.attr.actionBarItemBackground, C0101R.attr.actionMenuTextAppearance, C0101R.attr.actionMenuTextColor, C0101R.attr.actionModeStyle, C0101R.attr.actionModeCloseButtonStyle, C0101R.attr.actionModeBackground, C0101R.attr.actionModeSplitBackground, C0101R.attr.actionModeCloseDrawable, C0101R.attr.actionModeCutDrawable, C0101R.attr.actionModeCopyDrawable, C0101R.attr.actionModePasteDrawable, C0101R.attr.actionModeSelectAllDrawable, C0101R.attr.actionModeShareDrawable, C0101R.attr.actionModeFindDrawable, C0101R.attr.actionModeWebSearchDrawable, C0101R.attr.actionModePopupWindowStyle, C0101R.attr.textAppearanceLargePopupMenu, C0101R.attr.textAppearanceSmallPopupMenu, C0101R.attr.dialogTheme, C0101R.attr.dialogPreferredPadding, C0101R.attr.listDividerAlertDialog, C0101R.attr.actionDropDownStyle, C0101R.attr.dropdownListPreferredItemHeight, C0101R.attr.spinnerDropDownItemStyle, C0101R.attr.homeAsUpIndicator, C0101R.attr.actionButtonStyle, C0101R.attr.buttonBarStyle, C0101R.attr.buttonBarButtonStyle, C0101R.attr.selectableItemBackground, C0101R.attr.selectableItemBackgroundBorderless, C0101R.attr.borderlessButtonStyle, C0101R.attr.dividerVertical, C0101R.attr.dividerHorizontal, C0101R.attr.activityChooserViewStyle, C0101R.attr.toolbarStyle, C0101R.attr.toolbarNavigationButtonStyle, C0101R.attr.popupMenuStyle, C0101R.attr.popupWindowStyle, C0101R.attr.editTextColor, C0101R.attr.editTextBackground, C0101R.attr.textAppearanceSearchResultTitle, C0101R.attr.textAppearanceSearchResultSubtitle, C0101R.attr.textColorSearchUrl, C0101R.attr.searchViewStyle, C0101R.attr.listPreferredItemHeight, C0101R.attr.listPreferredItemHeightSmall, C0101R.attr.listPreferredItemHeightLarge, C0101R.attr.listPreferredItemPaddingLeft, C0101R.attr.listPreferredItemPaddingRight, C0101R.attr.dropDownListViewStyle, C0101R.attr.listPopupWindowStyle, C0101R.attr.textAppearanceListItem, C0101R.attr.textAppearanceListItemSmall, C0101R.attr.panelBackground, C0101R.attr.panelMenuListWidth, C0101R.attr.panelMenuListTheme, C0101R.attr.listChoiceBackgroundIndicator, C0101R.attr.colorPrimary, C0101R.attr.colorPrimaryDark, C0101R.attr.colorAccent, C0101R.attr.colorControlNormal, C0101R.attr.colorControlActivated, C0101R.attr.colorControlHighlight, C0101R.attr.colorButtonNormal, C0101R.attr.colorSwitchThumbNormal, C0101R.attr.alertDialogStyle, C0101R.attr.alertDialogButtonGroupStyle, C0101R.attr.alertDialogCenterButtons, C0101R.attr.alertDialogTheme, C0101R.attr.textColorAlertDialogListItem, C0101R.attr.buttonBarPositiveButtonStyle, C0101R.attr.buttonBarNegativeButtonStyle, C0101R.attr.buttonBarNeutralButtonStyle, C0101R.attr.autoCompleteTextViewStyle, C0101R.attr.buttonStyle, C0101R.attr.buttonStyleSmall, C0101R.attr.checkboxStyle, C0101R.attr.checkedTextViewStyle, C0101R.attr.editTextStyle, C0101R.attr.radioButtonStyle, C0101R.attr.ratingBarStyle, C0101R.attr.spinnerStyle, C0101R.attr.switchStyle};
            ThreeStateButton = new int[]{2130772354, 2130772355, 2130772356};
            Toolbar = new int[]{16842927, 16843072, C0101R.attr.title, C0101R.attr.subtitle, C0101R.attr.contentInsetStart, C0101R.attr.contentInsetEnd, C0101R.attr.contentInsetLeft, C0101R.attr.contentInsetRight, C0101R.attr.popupTheme, C0101R.attr.titleTextAppearance, C0101R.attr.subtitleTextAppearance, C0101R.attr.titleMargins, C0101R.attr.titleMarginStart, C0101R.attr.titleMarginEnd, C0101R.attr.titleMarginTop, C0101R.attr.titleMarginBottom, C0101R.attr.maxButtonHeight, C0101R.attr.collapseIcon, C0101R.attr.collapseContentDescription, C0101R.attr.navigationIcon, C0101R.attr.navigationContentDescription};
            View = new int[]{16842752, 16842970, C0101R.attr.paddingStart, C0101R.attr.paddingEnd, C0101R.attr.theme, C0101R.attr.backgroundTint, C0101R.attr.backgroundTintMode};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130772374;
            ViewPagerIndicator = iArr;
            ViewStubCompat = new int[]{16842960, 16842994, 16842995};
            com_facebook_like_view = new int[]{2130772375, 2130772376, 2130772377, 2130772378, 2130772379, 2130772380};
            com_facebook_login_view = new int[]{2130772381, 2130772382, 2130772383, 2130772384};
            com_facebook_profile_picture_view = new int[]{2130772385, 2130772386};
        }
    }
}
